[package]
name = "tsusu"
version = "0.1.0"
authors = ["Luna <git@l4.pm>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "2.0.2"
nix = "0.15.0"
signal-hook = "0.1.10"
